FROM python:3.12-alpine3.21
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY req.bot.txt .
RUN pip install --no-cache-dir -r req.bot.txt
COPY ./aiogram-bot .
CMD ["python", "run_bot.py"]